spring:
  application:
    name: harmonia-music-store
  
  # H2 database configuration
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  # JPA/Hibernate configuration
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  
  # Redis cache configuration (optional)
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
  
  # Validation configuration
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false

# Server configuration
server:
  port: 8080

# Logging configuration
logging:
  level:
    com.harmonia.store: INFO
    org.springframework.cache: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# OpenAPI/Swagger configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

# Custom configuration
app:
  cache:
    ttl: 300 # 5 minutes
  search:
    max-results: 100 